version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "https://trendapp-backend.onrender.com"
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
